engines:
  eslint:
    enabled: true
    channel: eslint-7
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/*.test.{js,jsx,ts,tsx}'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
